Fix #3: avoid TypeError exception when no int subset
When a DOCTYPE is matched but no internal subset, the result
of the match object's match['IntSubset'] is None.

This leads to a TypeError exception:

   TypeError: argument of type 'NoneType' is not iterable

If no internal subset could be found, continue with next
file. This avoids the above error.

* Raise version to 2.2.1
* Added integration tests with "real" XML files and output
* Use .group() on match object to be compatible with Python 3.5
  (match object is only scriptable on Python >=3.6)
* Fix traceback by moving log output after if clause
* the match variable can be empty (=None) so there is no
  match.groupdict(), giving an exception.
* add another test case without DOCTYPE declaration
* Add XML Catalog support
  * Query XML catalog(s) with the xmlcatalog tool
  * Introduce a new xmlcatalog() function
  * Add test cases
* Add missing testpaths keyword to "[tools:pytest]"
* Fix a deficiency when adding new entitiy filenames to a set
* Enable coverage with pytest-cov
* Introduce MAINCATALOG and -c/--catalog option (use it as default)
* Improve docstrings and log strings
* Support .editorconfig
* Check if XML file exists and catch exception